### ISSUE TITLE
[BUG] PixelVIP buga com o plugin de rankup, pois quando um player ativa vip, não consegue fazer /rankup eperde o rank em que estava ate o vip terminar

### ISSUE THREAD

**Issue by M0NST3RPT** [FabioZumbi12/PixelVip#67]
Os vips nao conseguem fazer /rankup
Os vips perdem o grupo de fly( caso um vip nao tenhas, mas o jogador tenha comprado vip)
Os vips nao perdem o rank em que estavam antes de virar vip ate o mesmo acabar

**Comment by heroslender** [comment]
Tenta desativar o uso de Vault na config:

```yaml
  Vault:
    use: false
    mode: 'set'
```

E colocar os comandos de definir/remover os grupos nas opções `cmdOnRemoveVip` e `commandsToRunOnChangeVip`:

```yaml
  # Command to run when a vip is removed by command.
  cmdOnRemoveVip: 'lp user {p} parent remove {vip}'

  # Run this commands on player change your vip to other.
  # Variables: {p|player} get the player name, {newvip} get the new vip, {oldvip} get the vip group before change.
  commandsToRunOnChangeVip:
  - 'lp user {p} parent add {newvip}'
  - 'lp user {p} parent remove {oldvip}'
```

Fazendo isso deves resolver o teu problema.
